import { Button } from "antd"
import axios from "axios"
import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-center">Hello world!</h1>
      <style jsx>{`
        #btn {
          color: green;
          background: red;
          height: 10em;
        }
      `}</style>
      <Button
        id="btn"
        onClick={() => {
          axios.get("/api/hello").then(({ data }) => {
            console.log(data)
          })
        }}
      >
        发送请求
      </Button>
    </div>
  )
}

export default Home
